### ISSUE TITLE
Bug: Static query build folder

### ISSUE THREAD

**Issue by syndia** [phenomic/phenomic#1081] opened 2017-06-09 13:37 UTC
With the static query build, there will be a folder `:prop_name` created with custom as name :prop_name (see image)

<img width="240" alt="schermafbeelding 2017-06-09 om 15 26 57" src="https://user-images.githubusercontent.com/1820680/26977729-32dfd004-4d29-11e7-8c9f-3622df273bd8.png">

And the static query is this like this: http://127.0.0.1:8080/phenomic/articles/by-tags/react/desc/limit-3.json

**Comment by syndia** [comment] 2017-06-09 14:02
Fo the pagination I think the problem is almost the same, I do not know how phenomic exactly use query, but if look it searching for a filename after-Zmly...A==.json:

static query: GET /phenomic/articles/by-default/1/desc/limit-3/after-Zmlyc3QtcG9zdA==.json

Folder structure see image:
<img width="239" alt="schermafbeelding 2017-06-09 om 15 58 08" src="https://user-images.githubusercontent.com/1820680/26978660-9b030f90-4d2c-11e7-98ce-42f0faba16b2.png">
<img width="725" alt="schermafbeelding 2017-06-09 om 15 58 25" src="https://user-images.githubusercontent.com/1820680/26978669-a34be29e-4d2c-11e7-9579-5b8127a7a0ad.png">

**Comment by MoOx** [comment] 2017-06-10 09:21
Actually we don't yet resolve values for metadata during static resolution. @bloodyowl could you take a look for this feature?
Also pagination is a bit hard to resolve completely and require a specific setup (eg: a single route for first page & all pages) to be correctly resolved. I will take a look on how to make this more intuitive and simple to setup.

**Comment by bloodyowl** [comment] 2017-06-10 09:24
this looks like a regression. we had this in the first place. will look into it.

**Comment by MoOx** [comment] 2017-06-10 09:25
I didn't see in the resolver file what is supposed to handle that. I may have missed something

**Comment by MoOx** [comment] 2017-08-10 04:16
Should be fixed in 1.0.0-alpha.5

**Closed by MoOx** 2017-08-10 04:16 UTC
Labels: type: bug
