### ISSUE TITLE
FAQ: Why I am seeing "No posts yet." while I have some .md files already?

### ISSUE THREAD

**Issue by kevin940726** [phenomic/phenomic#684] opened 2016-08-30 07:46 UTC
Hi, I really like this project but I cannot get it done by just follow the instruction.

First I tried to add several markdown posts to the app I've created, but it seems to not detecting the posts. It kept showing 'no posts'.

Then I tried to work on the boilerplate to figure out what went wrong. I followed the instruction on the [contributing](https://phenomic.io/contributing/) page. After running the command and it throw an error below.

```
> Phenomic@ prestart /Users/Kai/Work/SideProjects/phenomic/boilerplate
> npm -s run showcase-screenshots

module.js:440
    throw err;
    ^

Error: Cannot find module '/Users/Kai/Work/SideProjects/phenomic/boilerplate/scripts/showcase-screenshots.js'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Function.Module.runMain (module.js:575:10)
    at /Users/Kai/Work/SideProjects/phenomic/boilerplate/node_modules/babel-cli/lib/_babel-node.js:151:24
    at Object.<anonymous> (/Users/Kai/Work/SideProjects/phenomic/boilerplate/node_modules/babel-cli/lib/_babel-node.js:152:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

It seems to be an issue that the boilerplate package script is just copying the `package.json` from `docs/` folder, which has a `showcase-screenshots` script, but the boilerplate do not have.

Did I miss something? Any help can be great. Thanks in advance!

**Comment by MoOx** [comment] 2016-08-30 07:59
Hi @kevin940726!

I think for new pages, you need to restart webpack build, I think they are still issue with new files and require.context (since .md files are required via require.context webpack feature).

Can you give us more detail about your setup, file tree etc?

For the issue with the boilerplate, let me fix that, it's a stupid issue.

**Comment by MoOx** [comment] 2016-08-30 10:08
I pushed a fix so the boilerplate can be edited. But I would like to help you about your "no posts" problem :)

**Comment by kevin940726** [comment] 2016-08-30 15:41
I was outside, sorry for the late reply.

After updated, the `npm run boilerplate-start` script works great 👍 

Since it hasn't published to npm yet, after running `npm run boilerplate-start`, I `cd` into the `boilerplate` directory and make a change to the source directly. (I wonder if this is the correct way for now?)

After trying some ways, I finally get it working by **cleaning the cache**. I wonder if this feature is needed at all in development?

**Comment by thangngoc89** [comment] 2016-08-30 15:55
@kevin940726 how did you "cleaning the cache" ? We don't have any cache layer there.

`npm run boilerplate-start` is the script for starting boilerplate in development mode :)

**Comment by MoOx** [comment] 2016-08-30 16:06
In development **when contributing**. For a normal project (based on the boilerplate), just "npm start" is enough.

**Comment by kevin940726** [comment] 2016-08-30 16:35
The *Empty Cache and Hard Reload* button :joy: 
![more like this](http://www.code-pal.com/wp-content/uploads/2013/03/clear-cache-and-reload.png)

More precisely, whenever I open the browser without empty the cache, there is a **service worker** running in background to install the cache. You can see it in the **Application** tab of the chrome dev tool. I would be really really embarrassed if this is my problem :joy: 

Not sure if [the `cacheDirectory` option](https://github.com/MoOx/phenomic/blob/master/boilerplate/webpack.config.babel.js#L45-L46) is the issue as I don't really understand what does that mean. But when I remove that option, the build would failed due to a *service worker* problem. Please let me know if I have to paste the error log output here :wink:

**Comment by thangngoc89** [comment] 2016-08-30 16:41
The cacheDirectory is babel's cache. It's for node, nothing to do with the browser. And yeah. Cleaning service worker cache is a good choice.

**Comment by kevin940726** [comment] 2016-08-30 17:23
Maybe we shouldn't be running service worker in development? We can only install the offline plugin in production build. Wonder if this is a good idea?

**Comment by thangngoc89** [comment] 2016-08-30 17:29
SW isn't run in development mode. It maybe a leftover from a another session.

**Comment by MoOx** [comment] 2016-08-30 21:16
SW are run in development for debugging purpose. But this is causing too much trouble. I will deactivate this by default and allow to unable in dev via a flag. Here is an issue for that https://github.com/MoOx/phenomic/issues/689

Anyway @kevin940726 can we focus here about your initial issue? This dev mode on the boilerplate is mainly for contributing to the boilerplate, via some hacks, not really a way to try phenomic...

**Comment by kevin940726** [comment] 2016-08-31 05:30
@MoOx That would be great!

Sure, here is my folder structure of `content`. (from an app I created by npm, not cloning and building the boilerplate from source)
```
content
├── 404.md
├── assets
│   └── react.svg
├── index.md
├── loading.md
└── posts
    ├── Holy-Babel-Praise-the-ES6-Harmony.md
    └── I-Promise-you-it-s-going-to-be-great.md
```

I've clean up the cache (or service worker) and reload and rebuild (re-run `npm start`). But the page keep showing `No posts yet.`. I've seen my posts in the `collection` prop of the `PhenomicContext` component. And also in the `context` of `PageContainer` and `HomePage`. But the `pages` prop of the `PagesList` is an empty array. Any idea?

**Comment by thangngoc89** [comment] 2016-08-31 05:40
Do you have the source somewhere so that I can check it out. This is probably a bug

**Comment by MoOx** [comment] 2016-08-31 05:42
@thangngoc89 This is probably not a bug.

@kevin940726 If I understand correctly, you created your project using our setup?
I assume that according to the tree that contains the assets/react.svg :)
The current default boilerplate show you "No posts yet." if the current filtered collection does not return any posts. And, still according to the current default boilerplate, the filters are { layout: "Post" }. This means that you should add "layout: Post" in your posts/*.md files in the front-matter so the filtered collection will give you those posts.

See https://github.com/MoOx/phenomic/blob/13a8353d0c0c73752eca64b1b8c915f8701972c1/boilerplate/web_modules/layouts/Homepage/index.js#L16

If you don't want to add "layout: Post" in all your post, you can pass a function to `filter` like this

```js
    filter: (item) => item.__filename.startsWith("posts/")
```

(You might need to adjust the value used in startsWith() depending on your folder tree).

---

The SW has only been registered because you tried the boilerplate of the repo directly, so if you clean your cache correctly and does not use "offline" option in your project, this should not create any problem.

---

Please try to adjust the filters used in the collection call and tell us if that works for you.

**Comment by kevin940726** [comment] 2016-08-31 05:50
@MoOx Oh! That's the case! Thank you so much!

I knew that there is this option, but I thought every post layout was set to `Post` by default (which I think it should? At least in the `posts` folder).

**Comment by MoOx** [comment] 2016-08-31 05:52
We don't have a magic _posts folder like Jekyll. Some people will use "posts", some other will use "blog" or "news" etc. So I am not sure we should add this magic behavior. But I am not again changing the default boilerplate default filter if some of you think it should be changed.
Otherwise I guess adding this in the FAQ might help.

**Comment by kevin940726** [comment] 2016-08-31 06:05
I've noticed that there is a brand new `Getting Started` section in the documentation (which is so awesome! great job!). I think that the common layout (`Page` and `Post`) should be well-document in [this section](https://github.com/MoOx/phenomic/blob/master/docs/content/docs/getting-started.md#how-to-add-a-new-page-in-phenomic). And a clear example for what the default layout is and some other built-in layout alternatives. But that probably is just me being finicky 😅

**Comment by MoOx** [comment] 2016-08-31 06:06
Will add this in this section, good idea!

**Comment by MoOx** [comment] 2018-03-15 07:36
v1 should make this more clear

**Closed by MoOx** 2018-03-15 07:36 UTC
Labels: discussion, docs
